### PR TITLE
Added Windows support

### PR DESCRIPTION
**Pull request by dschreij**
Windows libraries are built using CMake. There are a few sidenotes to the current implementation:

- I created a static and dynamic build separately. Normally when you create a dynamic build, the compiler also creates a static .lib referencing the .dll file, but this doesn't happen for theora. My knowledge of C and compilers, or CMake, doesn't go far enough to know why, so I solved this by explicitly building the library again in static form. I don't know if this is redundant.
- I can't see how I could compile the theoraenc or theoradec binaries on windows, or if this is possible at all. So for windows, only the library is created, but no binaries to use it.

### CODE REVIEW

**Comment by dschreij** [comment]
@bgruening @jakirkham Windows support has been added, but AppVeyor and CircleCI don't start. Especially AppVeyor will be interesting of course ;)

**Comment by jakirkham** [comment]
Ah, so you need to [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) after changing `skip` in any way. Please you `conda-smithy` version `1.7.0` and please make sure your `.condarc` contains the section below before re-rendering. Can be removed after.

```yaml
channels:
  - conda-forge
  - defaults
```

Future versions of `conda-smithy` will not require this `.condarc` change.

**Comment by jakirkham** [comment]
Also we had some issues with CircleCI. Have already fixed this repo (just now verified). Manually triggered the build just now.

xref: https://github.com/conda-forge/status/issues/30

**Comment by dschreij** [comment]
I says `conda smithy rerender` doesn't have anything to do:

~~~
conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........
Fetching package metadata ...........

Re-rendered with conda-smithy 1.7.0.

No changes made. This feedstock is up-to-date.
~~~

**Comment by dschreij** [comment]
Alright, now it worked...

**Comment by jakirkham** [comment]
What changed?

**Comment by bgruening** [comment]
Cool beans @dschreij! Thanks for following up on this and sorry for my late rely, was on tour.

**Comment by dschreij** [comment]
I don't know. I rebased with master first and that undid all my changes to the meta.yaml (setting skip back to True for Windows). After I reapplied my changes to meta.yaml and reran conda-smithy it worked.

**Pull request merged**
