### PR TITLE
Try only documented requirements

### LINKED ISSUE #21: BUG: Pinning to zlib 1.2 is preventing future compat
Can it be lifted? For example trying to use `python==3.12.4` requires:
```
└─ python 3.12.4**  is not installable because it requires
   ├─ libexpat >=2.6.2,<3.0a0 , which conflicts with any installable versions previously reported;
   ├─ libzlib >=1.3.1,<2.0a0
```
but this package has:
```
│     │     │  └─ libtheora >=1.1.1,<1.2.0a0 , which requires
│     │     │     └─ zlib 1.2.* , which can be installed;
```
from

https://github.com/conda-forge/libtheora-feedstock/blob/987543a1ff53f5b0babed210b3e4f7c11eb0b0a2/recipe/meta.yaml#L32

@seanyen you added those pins... any idea if they can be relaxed?

I don't know anything about `libtheora` but could try to dig upstream a bit if it could help

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

At least according to https://xiph.org/theora/ which links to the 1.1.1 source:

> Both of implementations depend on the following libraries...
>
> * libogg-1.3.5
> * libvorbis-1.3.7
> * libSDL 1.2 or later for the playback example

So it doesn't seem like `zlib` or `libpng` dependencies should be needed to be specified. But this is a bit of a shot in the dark from my end. Hopefully the CIs will tell us. :shrug: 

Closes #21

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Well it at least built successfully. Thoughts on this one @bgruening @dschreij ?

**Comment by hoechenberger** [comment]
Friendly ping  @bgruening @dschreij 🙂

**Comment by traversaro** [comment]
To give a bit more of motivation of this PR, `libpng` and `zlib` are indeed dependencies of `libtheora`, but only if the debug option `OC_DUMP_IMAGES` is enabled, see https://gitlab.xiph.org/xiph/theora/-/commit/d0c140ab9844a3074983fd3acd252b9bf5693ba0 . In existing builds, this option is not enabled, see https://gitlab.xiph.org/xiph/theora/-/blob/v1.1.1/lib/internal.h#L440-445 and inspection of existing builds (libtheora 1.1.1 h7f98852_1005 conda-forge):

~~~
(libtheora) traversaro@IITBMP014LW012:~/miniforge3/envs/libtheora/lib$ readelf -s libtheora.so | grep oc_state_loop
   182: 0000000000017f20  1541 FUNC    LOCAL  DEFAULT   12 oc_state_loop_fi[...]
   219: 0000000000016580   707 FUNC    LOCAL  DEFAULT   12 oc_state_loop_fi[...]
   254: 0000000000016850     3 FUNC    LOCAL  DEFAULT   12 oc_state_loop_fi[...]
   351: 0000000000014240   476 FUNC    LOCAL  DEFAULT   12 oc_state_loop_fi[...]
(libtheora) traversaro@IITBMP014LW012:~/miniforge3/envs/libtheora/lib$ readelf -s libtheora.so | grep oc_frag_copy
   185: 000000000000b930    15 FUNC    LOCAL  DEFAULT   12 oc_frag_copy
   216: 000000000000b940    88 FUNC    LOCAL  DEFAULT   12 oc_frag_copy_c
   241: 00000000000172a0    76 FUNC    LOCAL  DEFAULT   12 oc_frag_copy_mmx
(libtheora) traversaro@IITBMP014LW012:~/miniforge3/envs/libtheora/lib$ readelf -s libtheora.so | grep oc_state_dump
(libtheora) traversaro@IITBMP014LW012:~/miniforge3/envs/libtheora/lib$
~~~


@conda-forge/core The PR is blocking libopencv 4.10 migration (see https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/69) and per https://conda-forge.org/docs/maintainer/maintainer_faq/#a-feedstock-has-been-abandoned-and-i-would-like-to-take-over-maintenance the period of ~1 week without any maintainer response have passed. Furthermore, the last PR merged by a mantainer (as opposed to a core member) dates back to 2020, see https://github.com/conda-forge/libtheora-feedstock/pull/11 . Given that, it would be great to merge this PR to unblock libopencv migration and other zlib==1.3 related conflicts, and if a new maintainer is necessary I am happy to volunteer (see https://github.com/conda-forge/libtheora-feedstock/pull/24)

**Comment by traversaro** [comment]
@conda-forge/core The PR is blocking libopencv 4.10 migration (see https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/69) and per https://conda-forge.org/docs/maintainer/maintainer_faq/#a-feedstock-has-been-abandoned-and-i-would-like-to-take-over-maintenance the period of ~1 week without any maintainer response have passed. Furthermore, the last PR merged by a mantainer (as opposed to a core member) dates back to 2020, see https://github.com/conda-forge/libtheora-feedstock/pull/11 . Given that, it would be great to merge this PR to unblock libopencv migration and other zlib==1.3 related conflicts, and if a new maintainer is necessary I am happy to volunteer (see https://github.com/conda-forge/libtheora-feedstock/pull/24)

**Comment by traversaro** [comment]
Thanks @ocefpaf!

**Pull request merged**
