### PR TITLE
Build on Windows

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/libtheora-feedstock/issues/4

Drops the skip and starts building on Windows.

@conda-forge-admin, please re-render.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems to failing. Any ideas?

```
CMake Error at CMakeLists.txt:84 (add_library):
  Cannot find source file:
    lib/collect.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at CMakeLists.txt:84 (add_library):
  No SOURCES given to target: THEORA
```

ref: https://ci.appveyor.com/project/conda-forge/libtheora-feedstock/build/1.0.5

**Comment by jakirkham** [comment]
Appears we cannot use inline assembly with Visual Studio on 64-bit. Not sure how to proceed. 😕

ref: https://stackoverflow.com/a/14292031
ref: https://ci.appveyor.com/project/conda-forge/libtheora-feedstock/build/1.0.9

**Comment by ihnorton** [comment]
vcpkg has a working CMakeList for theora:

https://github.com/Microsoft/vcpkg/blob/master/ports/libtheora/CMakeLists.txt

big differences are they build the VC-specific fragments from `lib/x86_vc`, and [only set `-DOC_X86_AS` on x86](https://github.com/Microsoft/vcpkg/blob/master/ports/libtheora/portfile.cmake#L21).

**Comment by jakirkham** [comment]
This was addressed in PR ( https://github.com/conda-forge/libtheora-feedstock/pull/10 ). Closing...

**Pull request closed without merging**
